version: '3'
services:
  fedora: &rhelconfig
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile-fedora
    volumes:
      - .:/home/builduser/configsnap
      - ./rpmbuild/RPMS:/home/builduser/rpmbuild/RPMS
      - ./rpmbuild/SRPMS:/home/builduser/rpmbuild/SRPMS
      - ./rpmbuild/SOURCES:/home/builduser/rpmbuild/SOURCES
  el8:
    <<: *rhelconfig
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile-el8
  el7:
    <<: *rhelconfig
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile-el7
  el6:
    <<: *rhelconfig
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile-el6
  buster:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile-buster
    volumes:
      - .:/home/builduser/configsnap
